(()=>{'use strict';
const data=window.LTTC_DATA, Q=Array.isArray(data?.questions)?data.questions:[], formulas=data?.formulas||{};
const $=id=>document.getElementById(id), esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const chapterTitles=['','Financial system, money & information','Time value of money & real interest rates','Loans & mortgages','Bonds, equity valuation & interest rates','Money-market instruments & yields','Risk & diversification','Financial statements, ratios & DuPont','Cash flow & working capital','Capital budgeting: NPV, IRR & payback'];
const KEY='lttc-practice-1045-v2'; const blank=()=>({results:{},marks:{}});let store=blank();
try{const p=JSON.parse(localStorage.getItem(KEY)||'null');if(p&&typeof p==='object'){store.results=p.results&&typeof p.results==='object'?p.results:{};store.marks=p.marks&&typeof p.marks==='object'?p.marks:{}}}catch(e){console.warn('Progress load failed:',e)}
let scope='all',chapter=null,list=[],idx=0,seed=0,drafts={};
const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(store));$('saveStatus').textContent='Saved on this device ✓'}catch(e){$('saveStatus').textContent='Storage unavailable — export your progress'}updateStats()};
const sourceGroup=q=>String(q.source||'').split('|')[0].trim()||'Unknown source';
const nLetters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';
const typeOf=q=>q.formula?'formula':'other';
const answered=id=>Object.prototype.hasOwnProperty.call(store.results,id);
const isRight=id=>answered(id)&&store.results[id]?.correct===true;
const isWrong=id=>answered(id)&&!isRight(id);
function updateStats(){const attempted=Q.filter(q=>answered(q.id)).length,correct=Q.filter(q=>isRight(q.id)).length,bookmarks=Q.filter(q=>store.marks[q.id]).length;
 $('totalStat').textContent=Q.length.toLocaleString('en-US');$('allCount').textContent=Q.length.toLocaleString('en-US');$('attemptedStat').textContent=attempted;$('attemptedNote').textContent=(Q.length?Math.round(attempted/Q.length*100):0)+'% completed';$('correctStat').textContent=correct;$('correctNote').textContent=(attempted?Math.round(correct/attempted*100):0)+'% of attempted';$('savedStat').textContent=bookmarks;$('bookmarksCount').textContent=bookmarks;$('unattemptedCount').textContent=Q.length-attempted;$('mistakesCount').textContent=Q.filter(q=>isWrong(q.id)).length;
}
function buildChapters(){let html='';for(let c=1;c<=9;c++){html+=`<button class="nav-item" data-chapter="${c}"><span>${String(c).padStart(2,'0')} · ${esc(chapterTitles[c])}</span><span class="nav-number">${Q.filter(q=>q.chapter===c).length}</span></button>`}$('chapterNav').innerHTML=html;}
function highlightNav(){document.querySelectorAll('[data-mode]').forEach(b=>b.classList.toggle('active',!chapter&&scope===b.dataset.mode));document.querySelectorAll('[data-chapter]').forEach(b=>b.classList.toggle('active',chapter===Number(b.dataset.chapter)));$('sectionName').textContent=chapter?'Chapter '+chapter+' — '+chapterTitles[chapter]:({all:'All questions',bookmarks:'Bookmarked questions',unattempted:'Not attempted',mistakes:'Review mistakes'}[scope]||'All questions');}
function setupSourceFilter(){const el=$('sourceFilter'),active=el.value,kind=$('kindFilter').value,arr=Array.from(new Set(Q.filter(q=>kind==='all'||q.kind===kind).map(sourceGroup))).sort((a,b)=>a.localeCompare(b));el.innerHTML='<option value="all">Any paper / bank</option>'+arr.map(s=>`<option value="${esc(s)}">${esc(s)}</option>`).join('');el.value=arr.includes(active)?active:'all';}
function matches(){let search=$('searchInput').value.trim().toLocaleLowerCase(),kind=$('kindFilter').value,src=$('sourceFilter').value,type=$('typeFilter').value;
return Q.filter(q=>(!chapter||q.chapter===chapter)&&(scope!=='bookmarks'||store.marks[q.id])&&(scope!=='unattempted'||!answered(q.id))&&(scope!=='mistakes'||isWrong(q.id))&&(kind==='all'||q.kind===kind)&&(src==='all'||sourceGroup(q)===src)&&(type==='all'||typeOf(q)===type)&&(!search||[q.id,q.parent,q.original,q.prompt,q.source,q.explanation,...q.options.map(o=>o.text)].join(' ').toLocaleLowerCase().includes(search)));
}
function shuffleGroups(items){const groups=new Map();items.forEach(q=>{const k=q.parent||q.id;if(!groups.has(k))groups.set(k,[]);groups.get(k).push(q)});const g=Array.from(groups.values());let x=0x9e3779b9+seed*97;const rnd=()=>{x=(1664525*x+1013904223)>>>0;return x/4294967296};for(let i=g.length-1;i>0;i--){const j=Math.floor(rnd()*(i+1));[g[i],g[j]]=[g[j],g[i]]}return g;}
function setupSet(){let a=matches();$('matchingCount').textContent=a.length.toLocaleString('en-US')+' matching';const limited=$('sizeFilter').value,random=$('shuffleToggle').checked;if(random||limited!=='all'){let groups=shuffleGroups(a);if(!random)groups=Array.from(groups).sort((x,y)=>Q.indexOf(x[0])-Q.indexOf(y[0]));const max=limited==='all'?Infinity:Number(limited);let out=[];for(const group of groups){if(out.length>=max)break;out.push(...group)}list=out;}else list=a;idx=0;render();}
function imgTag(img){if(!img?.src)return '';return `<img src="${esc(img.src)}" alt="${esc(img.alt||'Mathematical formula')}" loading="lazy" width="${Number(img.w)||180}" height="${Number(img.h)||40}">`}
function tableHtml(t){if(!Array.isArray(t)||!t.length)return '';return `<div class="table-scroll"><table class="data-table"><thead><tr>${(t[0]||[]).map(v=>`<th>${esc(v)}</th>`).join('')}</tr></thead><tbody>${t.slice(1).map(row=>'<tr>'+row.map(cell=>`<td>${esc(cell)}</td>`).join('')+'</tr>').join('')}</tbody></table></div>`}
function tablesHtml(ts){return(Array.isArray(ts)?ts:[]).map(tableHtml).join('')}
function formulaOptions(q){const f=formulas[q.formula];if(!f)return [];const options=[{correct:true,image:f.image,tex:f.tex},...(f.wrong||[]).map((tex,i)=>({correct:false,image:f.wrongImages?.[i],tex}))];let x=Array.from(options);const pos=Array.from(q.id).reduce((a,c)=>a+c.charCodeAt(0),0)%Math.max(1,x.length);x.splice(pos,0,x.shift());return x}
function formulaStage(q,d,result){if(!q.formula)return '';const f=formulas[q.formula],opts=formulaOptions(q);if(!f)return '<p class="phase-result bad">Formula metadata is missing. You can continue with the calculation choices.</p>';
let html=`<div class="step-heading">STEP 01 / CHOOSE THE FORMULA</div><p class="formula-help">Select the appropriate formula before answering the calculation question.</p><div class="choices">`;
html+=opts.map((fopt,i)=>{const selected=d.formulaChoice===i||result?.formulaChoice===i,marked=(d.formulaChecked||result)&&selected;return `<button class="formula-choice ${selected?'is-selected':''} ${marked?(fopt.correct?'is-right':'is-wrong'):''}" data-formula-choice="${i}" ${d.formulaChecked||result?'disabled':''}><span class="letter">${nLetters[i]}</span><span class="formula-image">${imgTag(fopt.image)||esc(fopt.tex)}</span></button>`}).join('')+'</div>';
if(result||d.formulaChecked){const selected=opts[d.formulaChoice??result?.formulaChoice],ok=selected?.correct===true;html+=`<p class="phase-result ${ok?'good':'bad'}">${ok?'✓ Correct formula.':'✕ Not the right formula for this problem.'} ${esc(f.why||'')}</p>`;if(!ok)html+=`<p class="formula-help">Correct formula:</p><div class="math-line">${imgTag(f.image)||esc(f.tex)}</div>`}
else html+=`<div class="action-row"><button class="button-primary" data-action="check-formula" ${Number.isInteger(d.formulaChoice)?'':'disabled'}>Check formula →</button></div>`;
return html;
}
function choiceLabel(o,i){const key=(o.key||nLetters[i]);return `<span class="letter">${esc(key)}</span><span class="choice-inner">${o.math&&o.image?imgTag(o.image):esc(o.text)}</span>`}
function answerStage(q,d,result){let html='<div class="step-heading">'+(q.formula?'STEP 02 / SOLVE THE QUESTION':'CHOOSE YOUR ANSWER')+'</div>';
if(q.formula&&!d.formulaChecked&&!result){return html+'<p class="muted-copy">Check the formula above to unlock the answer choices.</p>'}
const isDone=!!result,chosen=isDone?result.answer:d.answer;
html+='<div class="choices">'+q.options.map((o,i)=>{const selected=chosen===i,graded=isDone&&(selected||i===q.correct);return `<button class="choice ${selected?'is-selected':''} ${graded?(i===q.correct?'is-right':'is-wrong'):''}" data-answer="${i}" ${isDone?'disabled':''}>${choiceLabel(o,i)}</button>`}).join('')+'</div>';
if(!isDone){html+=`<div class="action-row"><button data-action="check-answer" class="button-primary" ${Number.isInteger(d.answer)?'':'disabled'}>Check answer →</button><span class="muted-copy">You'll see the explanation after submitting.</span></div>`}
return html;
}
function solutionHtml(q,result){if(!result)return '';const correct=!!result.correct;const ans=q.options[q.correct];let answer=esc(ans?.key||nLetters[q.correct])+'. '+esc(ans?.text||'');const formulaBad=q.formula&&!result.formulaCorrect;
return `<div class="solution"><div class="answer-line ${correct?'good':'bad'}">${correct?'✓ Correct answer.':formulaBad?'✕ Review the formula step and answer.':'✕ Review your answer.'}</div><h3>Answer & explanation</h3><p><strong>Correct option:</strong> ${answer}</p>${q.explanation?`<p>${esc(q.explanation)}</p>`:''}${q.mathSteps?.length?`<div class="step-heading">WORKED SOLUTION</div><div class="answer-steps">${q.mathSteps.map(i=>`<div class="math-line">${imgTag(i)}</div>`).join('')}</div>`:''}${q.answerTables?.length?`<div class="step-heading">COMPLETED TABLES</div>${tablesHtml(q.answerTables)}`:''}${q.note?`<p><strong>Source note:</strong> ${esc(q.note)}</p>`:''}${formulaBad?'<p><strong>Important:</strong> A wrong formula still counts as a mistake even if you selected the correct numerical answer. Try again and complete both stages correctly.</p>':''}<div class="action-row"><button class="button-quiet" data-action="retry">↺ Try this question again</button></div></div>`;
}
function questionHtml(q){const d=drafts[q.id]||{},result=store.results[q.id],mark=!!store.marks[q.id];const label=q.adapted?'Adapted practice':q.kind;const more=q.original!==q.prompt||q.tables?.length>0;
return `<div class="question-body"><div class="q-meta"><span class="q-id">${esc(q.id)}</span><span class="q-chip">${esc(label)}</span><span>Chapter ${q.chapter}</span><a class="source-link" href="source.pdf#page=${Math.max(1,Number(q.page)||1)}" target="_blank" rel="noopener">PDF page ${esc(q.page)} ↗</a><button class="bookmark-btn ${mark?'marked':''}" data-action="bookmark" aria-label="${mark?'Remove bookmark':'Bookmark this question'}" title="Bookmark">${mark?'★':'☆'}</button></div>${more?`<div class="original-label">ORIGINAL EXERCISE</div><p class="original-text">${esc(q.original)}</p>`:''}${tablesHtml(q.tables)}<h3 class="prompt-text ${more?'secondary':''}">${esc(q.prompt||q.original)}</h3>${formulaStage(q,d,result)}${answerStage(q,d,result)}${solutionHtml(q,result)}<p class="muted-copy" style="margin-top:22px">${esc(q.source)}</p></div>`;
}
function render(){updateStats();$('matchingCount').textContent=matches().length.toLocaleString('en-US')+' matching';$('setCount').textContent=list.length.toLocaleString('en-US')+' in this set';const q=list[idx];$('prevBtn').disabled=!q||idx===0;$('nextBtn').disabled=!q||idx===list.length-1;$('questionPosition').textContent=q?`Question ${idx+1} of ${list.length}`:'No questions';$('progressBar').style.width=(q?(idx+1)/list.length*100:0)+'%';$('questionSource').textContent=q?`${q.kind} · ${esc(q.id)}`:'';
if(!q){$('questionMount').innerHTML=`<div class="empty-state">${Q.length?'No matching questions. Adjust your filters or choose another chapter.':'No data available.'}</div>`;return}$('questionMount').innerHTML=questionHtml(q);}
function submitFormula(q){const d=drafts[q.id];if(!d||!Number.isInteger(d.formulaChoice))return;d.formulaChecked=true;render()}
function submitAnswer(q){const d=drafts[q.id];if(!d||!Number.isInteger(d.answer)||store.results[q.id])return;if(q.formula&&!d.formulaChecked)return;const chosenFormula=q.formula?formulaOptions(q)[d.formulaChoice]:null,formulaCorrect=!q.formula||!!chosenFormula?.correct;
store.results[q.id]={answer:d.answer,formulaChoice:Number.isInteger(d.formulaChoice)?d.formulaChoice:null,formulaCorrect,correct:d.answer===q.correct&&formulaCorrect,submittedAt:new Date().toISOString()};save();render()}
function handleQuestionClick(ev){const b=ev.target.closest('button');if(!b||b.disabled)return;const q=list[idx];if(!q)return;const d=drafts[q.id]||(drafts[q.id]={});if(b.dataset.formulaChoice!==undefined){if(store.results[q.id]||d.formulaChecked)return;d.formulaChoice=Number(b.dataset.formulaChoice);render();return}if(b.dataset.answer!==undefined){if(store.results[q.id])return;d.answer=Number(b.dataset.answer);render();return}switch(b.dataset.action){case'check-formula':submitFormula(q);break;case'check-answer':submitAnswer(q);break;case'bookmark':store.marks[q.id]=!store.marks[q.id];save();render();break;case'retry':delete store.results[q.id];delete drafts[q.id];save();render();break;}}
function exportProgress(){const content=JSON.stringify({format:'lttc-1045-v2',exportedAt:new Date().toISOString(),results:store.results,marks:store.marks},null,2),a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type:'application/json'}));a.href=url;a.download='LTTC-1045-progress.json';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),2500)}
async function importProgress(ev){const file=ev.target.files?.[0];if(!file)return;try{const parsed=JSON.parse(await file.text());if(parsed.format!=='lttc-1045-v2'||!parsed.results||!parsed.marks||typeof parsed.results!=='object'||typeof parsed.marks!=='object')throw Error('This is not an LTTC 1045 backup.');if(!confirm('Replace all current answers and bookmarks with the imported backup?'))return;store={results:parsed.results,marks:parsed.marks};save();setupSet();alert('Progress restored.')}catch(e){alert('Unable to import: '+e.message)}finally{ev.target.value=''}}
function closeMenu(){$('sidebar').classList.remove('open');$('sidebarShade').classList.remove('visible');$('mobileMenu').setAttribute('aria-expanded','false')}
function start(){if(!Q.length){$('totalStat').textContent='0';$('attemptedNote').textContent='Data unavailable';$('questionMount').innerHTML='<div class="error-alert"><strong>The question database did not load.</strong><p>Upload <code>data.js</code> alongside <code>index.html</code> and <code>app.js</code> in the root of your GitHub repository. Check the filename, capitalization and GitHub Pages deployment.</p></div>';return}
buildChapters();setupSourceFilter();document.querySelector('.sidebar').addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.chapter){chapter=Number(b.dataset.chapter);scope='all'}else if(b.dataset.mode){chapter=null;scope=b.dataset.mode}else return;highlightNav();setupSet();closeMenu()});
$('questionMount').addEventListener('click',handleQuestionClick);
for(const id of ['searchInput','kindFilter','sourceFilter','typeFilter','sizeFilter','shuffleToggle']){$(id).addEventListener(id==='searchInput'?'input':'change',()=>{if(id==='kindFilter')setupSourceFilter();setupSet()})}
$('newSetBtn').addEventListener('click',()=>{seed++;setupSet()});$('prevBtn').addEventListener('click',()=>{if(idx>0){idx--;render()}});$('nextBtn').addEventListener('click',()=>{if(idx<list.length-1){idx++;render()}});
$('exportBtn').addEventListener('click',exportProgress);$('importInput').addEventListener('change',importProgress);$('mobileMenu').addEventListener('click',()=>{const isOpen=$('sidebar').classList.toggle('open');$('sidebarShade').classList.toggle('visible',isOpen);$('mobileMenu').setAttribute('aria-expanded',String(isOpen))});$('sidebarShade').addEventListener('click',closeMenu);
highlightNav();setupSet()}
start();
})();
